#LLENANDO LOS PAISES
INSERT INTO PAIS(NOMBRE)
SELECT DISTINCT PAIS FROM TEMPORAL;

#LLENANDO EL SEXO QUE HAY EN EL DOCUMENTO
INSERT INTO SEXO(NOMBRE)
SELECT DISTINCT SEXO1 FROM TEMPORAL;

#LLENANDO ETNIAS
INSERT INTO ETNIA(NOMBRE)
SELECT DISTINCT RAZA1 FROM TEMPORAL;

#LLENADO DE LAS REGIONES DE PAISES
INSERT INTO REGION(NOMBRE, ID_PAIS)
SELECT DISTINCT T.REGION, P.ID_PAIS FROM TEMPORAL AS T, PAIS AS P
WHERE P.NOMBRE = T.PAIS;

#LLENANDO LOS PARTIDOS
INSERT INTO PARTIDO(NOMBRE, INICIALES, ID_PAIS)
SELECT DISTINCT T.NOMBRE_PARTIDO, T.PARTIDO, PAIS.ID_PAIS FROM TEMPORAL T, PAIS
WHERE PAIS.NOMBRE = T.PAIS;

#LLENANDO LAS ELECCIONES
INSERT INTO ELECCION(ID_PAIS, NOMBRE, ANIO)
SELECT DISTINCT PAIS.ID_PAIS, T.NOMBRE_ELECCION, T.ANIO_ELECCION FROM TEMPORAL T, PAIS
WHERE PAIS.NOMBRE = T.PAIS;

#LLENADO DE DEPARTAMENTOS
INSERT INTO DEPARTAMENTO(NOMBRE, ID_REGION)
SELECT DISTINCT T.DEPTO, R.ID_REGION FROM TEMPORAL T, REGION R, PAIS P
WHERE T.REGION = R.NOMBRE AND T.PAIS = P.NOMBRE AND P.ID_PAIS = R.ID_PAIS;

#LLENADO DE MUNICIPIOS
INSERT INTO MUNICIPIO(NOMBRE, ID_DEPARTAMENTO)
SELECT DISTINCT T.MUNICIPIO, D.ID_DEPARTAMENTO FROM TEMPORAL T, DEPARTAMENTO D
WHERE D.NOMBRE = T.DEPTO;

#LLENANDO EL DETALLE DE VOTOS
INSERT INTO DETALLES_VOTOS(ID_ELECCION, ID_MUNICIPIO, ID_PARTIDO, ID_SEXO, ID_ETNIA, TOTAL_N_PRIMARIO, TOTAL_N_MEDIO, TOTAL_N_UNIV, TOTAL_N_NAC)
SELECT E.ID_ELECCION, M.ID_MUNICIPIO, P.ID_PARTIDO, S.ID_SEXO, ET.ID_ETNIA, T.PRIMARIA, T.NIVEL_MEDIO, T.UNIVERSITARIOS, T.ANALFABETOS FROM ELECCION E, TEMPORAL T, PAIS PA, MUNICIPIO M, DEPARTAMENTO DEP, REGION RE, PARTIDO P, SEXO S, ETNIA ET
WHERE T.NOMBRE_ELECCION = E.NOMBRE AND T.ANIO_ELECCION = E.ANIO AND PA.NOMBRE = T.PAIS AND PA.ID_PAIS = E.ID_PAIS
AND RE.ID_PAIS = PA.ID_PAIS AND RE.NOMBRE = T.REGION AND T.DEPTO = DEP.NOMBRE AND DEP.ID_REGION = RE.ID_REGION AND M.ID_DEPARTAMENTO = DEP.ID_DEPARTAMENTO AND M.NOMBRE = T.MUNICIPIO
AND T.NOMBRE_PARTIDO = P.NOMBRE AND T.PARTIDO = P.INICIALES AND P.ID_PAIS = PA.ID_PAIS
AND T.SEXO1 = S.NOMBRE
AND T.RAZA1 = ET.NOMBRE;
